version = 0.1
[default.deploy.parameters]
stack_name = "serverless-crud-api"
resolve_s3 = true
s3_prefix = "serverless-crud-api"
region = "eu-west-3"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
