AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless CRUD API using AWS SAM

Globals:
  Function:
    Timeout: 10
    Runtime: python3.9

Resources:
  CrudFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler
      Description: Lambda function handling all CRUD operations
      Events:
        Create:
          Type: Api
          Properties:
            Path: /items
            Method: POST
        Read:
          Type: Api
          Properties:
            Path: /items/{id}
            Method: GET
        Update:
          Type: Api
          Properties:
            Path: /items/{id}
            Method: PUT
        Delete:
          Type: Api
          Properties:
            Path: /items/{id}
            Method: DELETE
      Environment:
        Variables:
          TABLE_NAME: !Ref ItemsTable
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:DeleteItem
              Resource: !GetAtt ItemsTable.Arn

  ItemsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ItemsTable
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

Outputs:
  ApiUrl:
    Description: "Base URL for the API Gateway"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
  CrudFunction:
    Description: "CRUD Lambda Function ARN"
    Value: !GetAtt CrudFunction.Arn
